name: 'Unity Mobile Build Number Bumper'
author: Breakstep Studios
description: 'Github action that bumps the AndroidBundleVersionCode & iOS Build Number by 1'
branding:
  icon: 'settings'
  color: 'gray-dark'
outputs:
  android-build-number:
    description: "The new build number for Android"
  ios-build-number:
    description: "The new build number for iOS"
runs:
  using: 'docker'
  image: 'Dockerfile'